### ISSUE TITLE
Tests have started to fail (with OpenAPI-Modern-0.037?)

### ISSUE THREAD

**Issue by andk** [karenetheridge/Mojolicious-Plugin-OpenAPI-Modern#15]
Sample fail report: http://www.cpantesters.org/cpan/report/9e09f88c-73fc-11ed-b886-aa634bd7b258

I then produced this pair of a pass and a fail report:

- http://www.cpantesters.org/cpan/report/e73804f6-740e-11ed-b1c3-de8577293f87
- http://www.cpantesters.org/cpan/report/62539c90-740f-11ed-b5e9-d98e77293f87

The two are generated with the same perl, first with OpenAPI-Modern-0.036, the second with OpenAPI-Modern-0.037. I don't think that there was any other influence between the two runs.

**Comment by karenetheridge** [comment]
fixed in version 0.004.
