### ISSUE TITLE
Autoload external $ref files

### ISSUE THREAD

**Issue by PanosBougas** [karenetheridge/Mojolicious-Plugin-OpenAPI-Modern#21]
Hello again,

Considering the following openapi schema
```yaml
openapi: "3.1.0"
info:
  version: "1.0.0"
  title: "Sample API"
  description: Buy or rent spacecrafts
  license:
    name: Apache 2.0
paths:
  /spacecraft/{id}:
    parameters:
      - $ref: components/parameters/path/id.yaml
    get:
      summary: Read a spacecraft
      operationId: getResourceById
      responses:
        "200":
          description: The spacecraft corresponding to the provided `id`
          content:
            application/json:
              schema:
                $ref: components/schemas/spacecraft.yml
```

This passes compilation but when trying to call `validate_request` inside the controller module
```perl
$controller->openapi->validate_request( $controller->req );
```
 I get this:
```
$VAR1 = 'EXCEPTION: unable to find resource /<full_path>/components/parameters/path/id.yaml';
```

Is this a bug?
or
Do I need to do [this](https://metacpan.org/pod/JSON::Schema::Modern#add_schema) in order to add external files in general?

```perl
$controller->openapi->evaluator->add_schema('/spacecraft/{id}' => 'components/schemas/spacecraft.yml');
```

**Comment by karenetheridge** [comment]
You can call add_schema, but the first argument is an identifier of a JSON Schema, and the second argument is the actual schema (the contents of the file, deserialized).

If you're trying to load another OpenAPI document -- which isn't a schema, but contains schemas -- you should construct another JSON::Schema::Modern::Document::OpenAPI object, passing it the same JSON::Schema object as you used before, so they can share data. That way when OpenAPI::Modern tries to resolve the $ref it will be able to find it.
